-- MySQL Script generated by MySQL Workbench
-- 07/27/14 19:40:28
-- Model: CV Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cvdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cvdb` ;
CREATE SCHEMA IF NOT EXISTS `cvdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cvdb` ;

-- -----------------------------------------------------
-- Table `cvdb`.`personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`personal` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`personal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthdate` DATE NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`address` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`professional_experiences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`professional_experiences` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`professional_experiences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `experience` VARCHAR(45) NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`jobs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`jobs` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `company_headquarter` VARCHAR(45) NOT NULL,
  `jobname` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`schools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`schools` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`schools` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `education` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`extras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cvdb`.`extras` ;

CREATE TABLE IF NOT EXISTS `cvdb`.`extras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
