-- MySQL Script generated by MySQL Workbench
-- 07/27/14 12:35:40
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cvdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cvdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cvdb` ;

-- -----------------------------------------------------
-- Table `cvdb`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvdb`.`personal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `birthdate` DATE NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvdb`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`professional_experiences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvdb`.`professional_experiences` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `experience` VARCHAR(45) NOT NULL,
  `level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvdb`.`jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `company_headquarter` VARCHAR(45) NOT NULL,
  `jobname` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`personal_to_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvdb`.`personal_to_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personal_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personal_to_address_address1_idx` (`address_id` ASC),
  INDEX `fk_personal_to_address_personal1_idx` (`personal_id` ASC),
  CONSTRAINT `fk_personal_to_address_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `cvdb`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_to_address_personal1`
    FOREIGN KEY (`personal_id`)
    REFERENCES `cvdb`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`personal_to_experiences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvdb`.`personal_to_experiences` (
  `id` INT NOT NULL,
  `personal_id` INT NOT NULL,
  `experience_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personal_to_experiences_personal1_idx` (`personal_id` ASC),
  INDEX `fk_personal_to_experiences_professional_experiences1_idx` (`experience_id` ASC),
  CONSTRAINT `fk_personal_to_experiences_personal1`
    FOREIGN KEY (`personal_id`)
    REFERENCES `cvdb`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_to_experiences_professional_experiences1`
    FOREIGN KEY (`experience_id`)
    REFERENCES `cvdb`.`professional_experiences` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cvdb`.`personal_to_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cvdb`.`personal_to_jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `personal_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personal_to_jobs_personal1_idx` (`personal_id` ASC),
  INDEX `fk_personal_to_jobs_jobs1_idx` (`job_id` ASC),
  CONSTRAINT `fk_personal_to_jobs_personal1`
    FOREIGN KEY (`personal_id`)
    REFERENCES `cvdb`.`personal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_to_jobs_jobs1`
    FOREIGN KEY (`job_id`)
    REFERENCES `cvdb`.`jobs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
